# Database
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&serverTimezone=Europe/Madrid&allowPublicKeyRetrieval=true
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

# JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# App URLs
corty.app.url=${FRONTEND_URL}
corty.admin.url=${ADMIN_URL}
corty.media.base-url=${BACKEND_URL}/api

# Media (Aseguramos que use un directorio temporal en la nube si no usas S3/Cloudinary)
corty.media.upload-dir=/app/uploads

# Swagger deshabilitado en producción
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
