#application.properties
# App config
spring.application.name=backend
spring.profiles.active=dev

# Media
corty.media.upload-dir=uploads
spring.config.import=optional:classpath:application-secrets.properties,optional:file:src/main/resources/application-secrets.properties

# Mail — Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# App URL (para links en emails)
#corty.app.url=http://localhost:4200
#corty.admin.url=http://localhost:4201
