spring.application.name=backend

# MySQL Config
spring.datasource.url=jdbc:mysql://localhost:3306/corty?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret
jwt.secret=xcZFtAVia;b86HHbY.0D9}8)Ote^ZZe@.Y]]S*4qPsN

# Media uploads
corty.media.upload-dir=uploads
corty.media.base-url=http://localhost:8080/api